-- friendspeak: SQLite port of yukon.sql (the MySQL schema shipped with yukon-server).

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(12) NOT NULL UNIQUE COLLATE NOCASE,
  email VARCHAR(254) DEFAULT NULL,
  password CHAR(60) NOT NULL,
  loginKey TEXT DEFAULT NULL,
  rank TINYINT NOT NULL DEFAULT 1,
  permaBan TINYINT NOT NULL DEFAULT 0,
  joinTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  coins INTEGER NOT NULL DEFAULT 500,
  head INTEGER NOT NULL DEFAULT 0,
  face INTEGER NOT NULL DEFAULT 0,
  neck INTEGER NOT NULL DEFAULT 0,
  body INTEGER NOT NULL DEFAULT 0,
  hand INTEGER NOT NULL DEFAULT 0,
  feet INTEGER NOT NULL DEFAULT 0,
  color INTEGER NOT NULL DEFAULT 1,
  photo INTEGER NOT NULL DEFAULT 0,
  flag INTEGER NOT NULL DEFAULT 0,
  ninjaRank TINYINT NOT NULL DEFAULT 0,
  ninjaProgress TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS auth_tokens (
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  selector CHAR(36) NOT NULL,
  validator CHAR(60) NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userId, selector)
);

CREATE TABLE IF NOT EXISTS bans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  issued DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
  moderatorId INTEGER DEFAULT NULL REFERENCES users (id) ON DELETE SET NULL ON UPDATE SET NULL,
  message VARCHAR(60) DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS bans_userId ON bans (userId);

CREATE TABLE IF NOT EXISTS buddies (
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  buddyId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (userId, buddyId)
);

CREATE TABLE IF NOT EXISTS cards (
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  cardId INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  memberQuantity INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (userId, cardId)
);

CREATE TABLE IF NOT EXISTS furnitures (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  furnitureId INTEGER NOT NULL,
  x SMALLINT NOT NULL DEFAULT 0,
  y SMALLINT NOT NULL DEFAULT 0,
  rotation SMALLINT NOT NULL DEFAULT 1,
  frame SMALLINT NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS furnitures_userId ON furnitures (userId);

CREATE TABLE IF NOT EXISTS furniture_inventories (
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  itemId INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  PRIMARY KEY (userId, itemId)
);

CREATE TABLE IF NOT EXISTS igloos (
  userId INTEGER NOT NULL PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  type INTEGER NOT NULL DEFAULT 1,
  flooring INTEGER NOT NULL DEFAULT 0,
  music INTEGER NOT NULL DEFAULT 0,
  location INTEGER NOT NULL DEFAULT 1,
  locked TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS igloo_inventories (
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  iglooId INTEGER NOT NULL,
  PRIMARY KEY (userId, iglooId)
);

CREATE TABLE IF NOT EXISTS ignores (
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ignoreId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (userId, ignoreId)
);

CREATE TABLE IF NOT EXISTS inventories (
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  itemId INTEGER NOT NULL,
  PRIMARY KEY (userId, itemId)
);

CREATE TABLE IF NOT EXISTS postcards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  senderId INTEGER DEFAULT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  postcardId INTEGER NOT NULL,
  sendDate DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now')),
  details VARCHAR(255) DEFAULT NULL,
  hasRead TINYINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS postcards_userId ON postcards (userId);

CREATE TABLE IF NOT EXISTS pets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  typeId INTEGER NOT NULL,
  name VARCHAR(12) NOT NULL,
  adoptionDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  energy TINYINT NOT NULL DEFAULT 100,
  health TINYINT NOT NULL DEFAULT 100,
  rest TINYINT NOT NULL DEFAULT 100,
  feedPostcardId INTEGER DEFAULT NULL REFERENCES postcards (id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS pets_userId ON pets (userId);

CREATE TABLE IF NOT EXISTS worlds (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  population SMALLINT NOT NULL DEFAULT 0
);

CREATE TRIGGER IF NOT EXISTS trigger_users_insert AFTER INSERT ON users FOR EACH ROW BEGIN
  INSERT INTO igloos (userId) VALUES (NEW.id);
  INSERT INTO inventories (userId, itemId) VALUES (NEW.id, NEW.color);
  INSERT INTO postcards (userId, postcardId) VALUES (NEW.id, 125);
END;
